"""
Testing environment variables to figure out how to distinguish between parent shells.
"""

data = {
    "git_bash": {
        "ACLOCAL_PATH": "C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal",
        "ALLUSERSPROFILE": "C:\\ProgramData",
        "APPDATA": "C:\\Users\\eetyg\\AppData\\Roaming",
        "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
        "COMMONPROGRAMFILES(X86)": "C:\\Program Files (x86)\\Common Files",
        "COMMONPROGRAMW6432": "C:\\Program Files\\Common Files",
        "COMPUTERNAME": "DESKTOP-LCH5JCE",
        "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe",
        "CONDA_DEFAULT_ENV": "base",
        "CONDA_EXE": "C:/Users/eetyg/miniconda/Scripts/conda.exe",
        "CONDA_PREFIX": "C:\\Users\\eetyg\\miniconda",
        "CONDA_PROMPT_MODIFIER": "(base) ",
        "CONDA_PYTHON_EXE": "C:\\Users\\eetyg\\miniconda\\python.exe",
        "CONDA_ROOT": "C:\\Users\\eetyg\\miniconda",
        "CONDA_SHLVL": "1",
        "CONFIG_SITE": "C:/Program Files/Git/etc/config.site",
        "DISPLAY": "needs-to-be-defined",
        "DRIVERDATA": "C:\\Windows\\System32\\Drivers\\DriverData",
        "EXEPATH": "C:\\Program Files\\Git\\bin",
        "HOME": "C:\\Users\\eetyg",
        "HOMEDRIVE": "C:",
        "HOMEPATH": "\\Users\\eetyg",
        "HOSTNAME": "DESKTOP-LCH5JCE",
        "INFOPATH": "C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info",
        "LANG": "en_US.UTF-8",
        "LOCALAPPDATA": "C:\\Users\\eetyg\\AppData\\Local",
        "LOGONSERVER": "\\\\DESKTOP-LCH5JCE",
        "MANPATH": "C:\\Program Files\\Git\\mingw64\\local\\man;C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man",
        "MINGW_CHOST": "x86_64-w64-mingw32",
        "MINGW_PACKAGE_PREFIX": "mingw-w64-x86_64",
        "MINGW_PREFIX": "C:/Program Files/Git/mingw64",
        "MSYSTEM": "MINGW64",
        "MSYSTEM_CARCH": "x86_64",
        "MSYSTEM_CHOST": "x86_64-w64-mingw32",
        "MSYSTEM_PREFIX": "C:/Program Files/Git/mingw64",
        "NUMBER_OF_PROCESSORS": "24",
        "OLDPWD": "C:/Users/eetyg/code/algos",
        "ONEDRIVE": "C:\\Users\\eetyg\\OneDrive",
        "ONEDRIVECONSUMER": "C:\\Users\\eetyg\\OneDrive",
        "ORIGINAL_PATH": "C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\eetyg\\bin;C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Program Files\\nodejs;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\Git\\cmd;C:\\Users\\eetyg\\.cargo\\bin;C:\\Users\\eetyg\\miniconda\\condabin;C:\\Users\\eetyg\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\eetyg\\AppData\\Local\\Programs\\VSCode\\bin;C:\\Users\\eetyg\\AppData\\Roaming\\npm;C:\\Users\\eetyg\\.deno\\bin;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin",
        "ORIGINAL_TEMP": "C:/Users/eetyg/AppData/Local/Temp",
        "ORIGINAL_TMP": "C:/Users/eetyg/AppData/Local/Temp",
        "OS": "Windows_NT",
        "PATH": "C:\\Users\\eetyg\\miniconda;C:\\Users\\eetyg\\miniconda\\Library\\mingw-w64\\bin;C:\\Users\\eetyg\\miniconda\\Library\\usr\\bin;C:\\Users\\eetyg\\miniconda\\Library\\bin;C:\\Users\\eetyg\\miniconda\\Scripts;C:\\Users\\eetyg\\miniconda\\bin;C:\\Users\\eetyg\\miniconda\\condabin;C:\\Users\\eetyg\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\eetyg\\bin;C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Program Files\\nodejs;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\Git\\cmd;C:\\Users\\eetyg\\.cargo\\bin;C:\\Users\\eetyg\\miniconda\\condabin;C:\\Users\\eetyg\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\eetyg\\AppData\\Local\\Programs\\VSCode\\bin;C:\\Users\\eetyg\\AppData\\Roaming\\npm;C:\\Users\\eetyg\\.deno\\bin;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl",
        "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
        "PKG_CONFIG_PATH": "C:\\Program Files\\Git\\mingw64\\lib\\pkgconfig;C:\\Program Files\\Git\\mingw64\\share\\pkgconfig",
        "PLINK_PROTOCOL": "ssh",
        "PROCESSOR_ARCHITECTURE": "AMD64",
        "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 63 Stepping 2, GenuineIntel",
        "PROCESSOR_LEVEL": "6",
        "PROCESSOR_REVISION": "3f02",
        "PROGRAMDATA": "C:\\ProgramData",
        "PROGRAMFILES": "C:\\Program Files",
        "PROGRAMFILES(X86)": "C:\\Program Files (x86)",
        "PROGRAMW6432": "C:\\Program Files",
        "PS1": "(base) \\[\\033]0;$TITLEPREFIX:$PWD\\007\\]\\n\\[\\033[32m\\]\\u@\\h \\[\\033[35m\\]$MSYSTEM \\[\\033[33m\\]\\w\\[\\033[36m\\]`__git_ps1`\\[\\033[0m\\]\\n$ ",
        "PSMODULEPATH": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
        "PUBLIC": "C:\\Users\\Public",
        "PWD": "C:/Users/eetyg/code/algos/leetcode",
        "PYCHARM COMMUNITY EDITION": "C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin;",
        "PYTHONIOENCODING": "UTF-8",
        "SESSIONNAME": "Console",
        "SHELL": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
        "SHLVL": "1",
        "SSH_ASKPASS": "C:/Program Files/Git/mingw64/bin/git-askpass.exe",
        "SYSTEMDRIVE": "C:",
        "SYSTEMROOT": "C:\\WINDOWS",
        "TEMP": "C:\\Users\\eetyg\\AppData\\Local\\Temp",
        "TERM": "xterm-256color",
        "TMP": "C:\\Users\\eetyg\\AppData\\Local\\Temp",
        "TMPDIR": "C:\\Users\\eetyg\\AppData\\Local\\Temp",
        "USERDOMAIN": "DESKTOP-LCH5JCE",
        "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-LCH5JCE",
        "USERNAME": "eetyg",
        "USERPROFILE": "C:\\Users\\eetyg",
        "WINDIR": "C:\\WINDOWS",
        "WSLENV": "WT_SESSION::WT_PROFILE_ID",
        "WT_PROFILE_ID": "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}",
        "WT_SESSION": "b116b6e7-963a-4264-be43-03ab2a381e27",
        "_": "C:/Users/eetyg/miniconda/python",
        "_CE_CONDA": "",
        "_CE_M": ""
    },
    "cmd.exe": {
        "ALLUSERSPROFILE": "C:\\ProgramData",
        "APPDATA": "C:\\Users\\eetyg\\AppData\\Roaming",
        "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
        "COMMONPROGRAMFILES(X86)": "C:\\Program Files (x86)\\Common Files",
        "COMMONPROGRAMW6432": "C:\\Program Files\\Common Files",
        "COMPUTERNAME": "DESKTOP-LCH5JCE",
        "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe",
        "CONDA_DEFAULT_ENV": "base",
        "CONDA_EXE": "C:\\Users\\eetyg\\miniconda\\Scripts\\conda.exe",
        "CONDA_PREFIX": "C:\\Users\\eetyg\\miniconda",
        "CONDA_PROMPT_MODIFIER": "(base) ",
        "CONDA_PYTHON_EXE": "C:\\Users\\eetyg\\miniconda\\python.exe",
        "CONDA_ROOT": "C:\\Users\\eetyg\\miniconda",
        "CONDA_SHLVL": "1",
        "DRIVERDATA": "C:\\Windows\\System32\\Drivers\\DriverData",
        "HOMEDRIVE": "C:",
        "HOMEPATH": "\\Users\\eetyg",
        "LOCALAPPDATA": "C:\\Users\\eetyg\\AppData\\Local",
        "LOGONSERVER": "\\\\DESKTOP-LCH5JCE",
        "NUMBER_OF_PROCESSORS": "24",
        "ONEDRIVE": "C:\\Users\\eetyg\\OneDrive",
        "ONEDRIVECONSUMER": "C:\\Users\\eetyg\\OneDrive",
        "OS": "Windows_NT",
        "PATH": "C:\\Users\\eetyg\\miniconda;C:\\Users\\eetyg\\miniconda\\Library\\mingw-w64\\bin;C:\\Users\\eetyg\\miniconda\\Library\\usr\\bin;C:\\Users\\eetyg\\miniconda\\Library\\bin;C:\\Users\\eetyg\\miniconda\\Scripts;C:\\Users\\eetyg\\miniconda\\bin;C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_1.11.3471.0_x64__8wekyb3d8bbwe;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\dotnet;C:\\Program Files\\nodejs;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\Git\\cmd;C:\\Users\\eetyg\\.cargo\\bin;C:\\Users\\eetyg\\miniconda\\condabin;C:\\Users\\eetyg\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\eetyg\\AppData\\Local\\Programs\\VSCode\\bin;C:\\Users\\eetyg\\AppData\\Roaming\\npm;C:\\Users\\eetyg\\.deno\\bin;.;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin;.",
        "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
        "PROCESSOR_ARCHITECTURE": "AMD64",
        "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 63 Stepping 2, GenuineIntel",
        "PROCESSOR_LEVEL": "6",
        "PROCESSOR_REVISION": "3f02",
        "PROGRAMDATA": "C:\\ProgramData",
        "PROGRAMFILES": "C:\\Program Files",
        "PROGRAMFILES(X86)": "C:\\Program Files (x86)",
        "PROGRAMW6432": "C:\\Program Files",
        "PROMPT": "(base) $P$G",
        "PSMODULEPATH": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
        "PUBLIC": "C:\\Users\\Public",
        "PYCHARM COMMUNITY EDITION": "C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin;",
        "SESSIONNAME": "Console",
        "SYSTEMDRIVE": "C:",
        "SYSTEMROOT": "C:\\WINDOWS",
        "TEMP": "C:\\Users\\eetyg\\AppData\\Local\\Temp",
        "TMP": "C:\\Users\\eetyg\\AppData\\Local\\Temp",
        "USERDOMAIN": "DESKTOP-LCH5JCE",
        "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-LCH5JCE",
        "USERNAME": "eetyg",
        "USERPROFILE": "C:\\Users\\eetyg",
        "WINDIR": "C:\\WINDOWS",
        "WSLENV": "WT_SESSION::WT_PROFILE_ID",
        "WT_PROFILE_ID": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
        "WT_SESSION": "cd1ec228-95c8-4f35-ad24-eae8e80f6762"
    },
    "PS": {
        "ALLUSERSPROFILE": "C:\\ProgramData",
        "APPDATA": "C:\\Users\\eetyg\\AppData\\Roaming",
        "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_15044_XVOVLOGQSUGITOOF",
        "COLORTERM": "truecolor",
        "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
        "COMMONPROGRAMFILES(X86)": "C:\\Program Files (x86)\\Common Files",
        "COMMONPROGRAMW6432": "C:\\Program Files\\Common Files",
        "COMPUTERNAME": "DESKTOP-LCH5JCE",
        "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe",
        "CONDA_ROOT": "C:\\Users\\eetyg\\miniconda",
        "DRIVERDATA": "C:\\Windows\\System32\\Drivers\\DriverData",
        "GIT_ASKPASS": "c:\\Users\\eetyg\\AppData\\Local\\Programs\\VSCode\\resources\\app\\extensions\\git\\dist\\askpass.sh",
        "HOMEDRIVE": "C:",
        "HOMEPATH": "\\Users\\eetyg",
        "LANG": "en_US.UTF-8",
        "LOCALAPPDATA": "C:\\Users\\eetyg\\AppData\\Local",
        "LOGONSERVER": "\\\\DESKTOP-LCH5JCE",
        "NUMBER_OF_PROCESSORS": "24",
        "ONEDRIVE": "C:\\Users\\eetyg\\OneDrive",
        "ONEDRIVECONSUMER": "C:\\Users\\eetyg\\OneDrive",
        "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
        "OS": "Windows_NT",
        "PATH": "C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\Git\\cmd;C:\\Users\\eetyg\\.cargo\\bin;C:\\Users\\eetyg\\miniconda\\condabin;C:\\Users\\eetyg\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\eetyg\\AppData\\Local\\Programs\\VSCode\\bin;C:\\Users\\eetyg\\AppData\\Roaming\\npm;C:\\Users\\eetyg\\.deno\\bin;;C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin;",
        "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
        "PROCESSOR_ARCHITECTURE": "AMD64",
        "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 63 Stepping 2, GenuineIntel",
        "PROCESSOR_LEVEL": "6",
        "PROCESSOR_REVISION": "3f02",
        "PROGRAMDATA": "C:\\ProgramData",
        "PROGRAMFILES": "C:\\Program Files",
        "PROGRAMFILES(X86)": "C:\\Program Files (x86)",
        "PROGRAMW6432": "C:\\Program Files",
        "PSMODULEPATH": "C:\\Users\\eetyg\\OneDrive\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
        "PUBLIC": "C:\\Users\\Public",
        "PYCHARM COMMUNITY EDITION": "C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.3\\bin;",
        "PYTHONIOENCODING": "UTF-8",
        "PYTHONUNBUFFERED": "1",
        "SESSIONNAME": "Console",
        "SYSTEMDRIVE": "C:",
        "SYSTEMROOT": "C:\\WINDOWS",
        "TEMP": "C:\\Users\\eetyg\\AppData\\Local\\Temp",
        "TERM_PROGRAM": "vscode",
        "TERM_PROGRAM_VERSION": "1.65.2",
        "TMP": "C:\\Users\\eetyg\\AppData\\Local\\Temp",
        "USERDOMAIN": "DESKTOP-LCH5JCE",
        "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-LCH5JCE",
        "USERNAME": "eetyg",
        "USERPROFILE": "C:\\Users\\eetyg",
        "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
        "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\eetyg\\AppData\\Local\\Programs\\VSCode\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
        "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\eetyg\\AppData\\Local\\Programs\\VSCode\\Code.exe",
        "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-553cf3cb40-sock",
        "WINDIR": "C:\\WINDOWS"
    },
}


def main():
    from conda.common.serialize import json_dump
    gb, cmd, ps = data["git_bash"].keys(), data["cmd.exe"].keys(), data["PS"].keys()
    print("git_bash:", json_dump(list(gb - cmd - ps)))  # PS1, SHELL, PWD
    print("cmd.exe:", json_dump(list(cmd - gb - ps)))  # PROMPT
    print("PS:", json_dump(list(ps - cmd - gb)))  # ??


if __name__ == "__main__":
    main()
